WORD_DIM = 256
EMBED_FILE = 'word_embed'
MIN_COUNT = 5

MAX_SEQ_LEN = 39
EPOCH = 10
RNN_SIZE = 256
RNN_LAYER = 2
BATCH_SIZE = 256
LEARNING_RATE = 5e-4
KEEP_PROB = 0.5
DISPLAY_LOSS_PERIOD = 100
VALID_PERIOD = 1

SEMI_EPOCH = 5
CONFIDENCE_THRESHOLD = 0.995

LOAD_MODEL = True
VALID_MODEL = True