ENCODER_MAX_TIME_STEP = 246
DECODER_MAX_TIME_STEP = 13

DICT_SIZE = 2391
EMBED_DIM = 128

BATCH_SIZE = 512
RNN_SIZE = 256
RNN_LAYER = 2
LEARNING_RATE = 1e-3
KEEP_PROB = 0.75

EPOCH = 75
VALID_MODEL = False
LOAD_MODEL = False

DOWN_SAMPLE = True
ADD_NOISE = True